name: PiTemp
version: 1.1
author: Zazsona
main: com.zazsona.pitemp.Core
api-version: 1.17
commands:
  PiTemp:
    description: Configure PiTemp
permissions:
  PiTemp.Config:
    description: Configure PiTemp
    default: op